name: CI

on: 
  push:
    branches-ignore:
      - master
    tags-ignore:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Configure Node
      uses: actions/setup-node@v2
      with:
        cache: "yarn"
        node-version: "14"

    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    
    - name: Build
      run:  yarn build