name: Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: aws-actions/setup-sam@v1

      - name: Configure Git User
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Configure Node
        uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: "14"
  
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build
        run:  yarn build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Package
        run: yarn package
        env:
          CUTWATER_BUILD_CONFIG: >
            {
              "sam-package": {
                "parameters": {
                  "s3Bucket": "${{ secrets.S3_BUCKET }}"
                }
              }
            }

      - name: Release
        run: yarn release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run:  yarn publish:aws
